apiVersion: v1
kind: Pod
metadata:
  name: vol-pod-ch14

spec:
  volumes:
  - name: cm-vol
    configMap:
      name: info-cm-ch14
  - name: sec-vol
    secret:
      secretName: user-secret-ch14

  containers:
  - volumeMounts:
    - mountPath: /tmp/cm-items
      name: cm-vol
    - mountPath: /tmp/sec-items
      name: sec-vol

    image: busybox
    name: busy
    imagePullPolicy: IfNotPresent
    command: ["/bin/sleep", "300"]

