apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: dev-qt
  namespace: ns-test
spec:
  hard:
    requests.cpu: 10
    requests.memory: 2Gi
    limits.cpu: 10
    limits.memory: 20Gi

    requests.storage: 100Gi
    persistentvolumeclaims: 100

    pods: 50
    configmaps: 100
    secrets: 100
    services: 100

    count/jobs.batch: 1
    count/cronjobs.batch: 1
    count/deployments.apps: 1

