apiVersion: v1
kind: ConfigMap
metadata:
  name: ngx-probe-conf

data:
  default.conf: |
    server {
      listen 80;
      location = /ready {
        return 200 'I am ready';
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: ngx-pod-probe

spec:
  volumes:
  - name: ngx-probe-conf-vol
    configMap:
      name: ngx-probe-conf

  containers:
  - image: nginx:alpine
    name: ngx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /etc/nginx/conf.d
      name: ngx-probe-conf-vol

    startupProbe:
      periodSeconds: 3
      timeoutSeconds: 1
      exec:
        command: ["cat", "/var/run/nginx.pid"]
        #command: ["cat", "/var/run/nginx.pid-xxx"]

    livenessProbe:
      periodSeconds: 10
      timeoutSeconds: 1
      initialDelaySeconds: 5
      tcpSocket:
        port: 80
        #port: 801

    readinessProbe:
      periodSeconds: 5
      timeoutSeconds: 1
      initialDelaySeconds: 10
      httpGet:
        path: /ready
        #path: /ready-xxx
        port: 80

