apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ngx-svc-ch27
  name: ngx-svc-ch27
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ngx-ch27
status:
  loadBalancer: {}

