apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: sleep-cj-ch13
spec:
  schedule: '*/1 * * * *'
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: sleep-cj-ch13
    spec:
      completions: 3
      parallelism: 2
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: busybox
            name: sleep-cj-ch13
            resources: {}
            imagePullPolicy: IfNotPresent
            command:
              - sh
              - -c
              - sleep 90 && echo done
          restartPolicy: OnFailure

