# chrono @ 2022-04

# you can change it to secret
apiVersion: v1
kind: ConfigMap
metadata:
  name: maria-cm-15

data:
  DATABASE: 'db'
  USER: 'wp'
  PASSWORD: '123'
  ROOT_PASSWORD: '123'

---

apiVersion: v1
kind: Pod
metadata:
  name: maria-pod-ch15
  labels:
    app: wordpress
    role: database

spec:
  containers:
  - image: mariadb:10
    name: maria
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3306

    envFrom:
    - prefix: 'MARIADB_'
      configMapRef:
        name: maria-cm-15

---

