# docker build -t ngx-app:1.0 -f Dockerfile-nginx .

ARG IMAGE_BASE="nginx"
ARG IMAGE_TAG="1.22.1"

FROM ${IMAGE_BASE}:${IMAGE_TAG}

ENV APP_VERSION=1.0

COPY ./a.txt /tmp

RUN cd /usr/share/nginx/html \
    && echo "hello, nginx." > b.txt

EXPOSE 8081 8082 8083

#CMD echo "env: APP_VERSION: ${APP_VERSION}, IMAGE_BASE: ${IMAGE_BASE}"
#ENTRYPOINT echo "env: APP_VERSION: ${APP_VERSION}, IMAGE_BASE: ${IMAGE_BASE}"

