apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ngx-dep-ch18
  name: ngx-dep-ch18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngx-dep-ch18
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ngx-dep-ch18
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        resources: {}

